# Generated by Django 2.2.1 on 2019-08-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
